### ISSUE TITLE
Use `_` for private methods rather than `__`

### ISSUE THREAD

**Issue by davidroeca** [guruhq/py-sdk#51]
This API wrapper defines a `__get` method that I'm trying to leverage to implement consistent behavior in an endpoint that is not currently supported.

Here is the code that I'd have to write

```python
  class EnhancedClient(guru.Guru):
      """Subclass of client which includes team stats."""

      def get_team_stats(self):
          """See https://developer.getguru.com/reference/getv1teamsgetteamstats """
          url = "%s/teams/%s/stats" % (self.base_url, self.get_team_id())
          response = self._Guru__get(url, cache=True)
          return response.json()
```
Ideally, I could change the second to last line:
```diff
-          response = self._Guru__get(url, cache=True)
+          response = self.__get(url, cache=True)
```

But this is not possible due to python's name mangling. As someone who would want to enhance the `Guru` class, I'd prefer if `__get` were defined as `_get` instead.

Though to solve my specific issue, it would be nice for this API wrapper to implement the team stats endpoint.

**Comment by markhornak** [comment]
added Team Stats, still debating on changing internal __get methods to just _get.
