### ISSUE TITLE
BoardGroup is incorrectly classifying all its items as Board types

### ISSUE THREAD

**Issue by dephekt** [guruhq/py-sdk#72]
The following code is how BoardGroup defines its items currently:

```python
self.items = [Board(b, guru) for b in data.get("items") or []]
```
Which contains a hard assumption that every item of the BoardGroup is a Board.

The problem is when calling `get_home_board()` on a collection, in the raw response from the REST API, some of the items for a particular board group may not actually be boards, yet they are being inappropriately shoe-horned into a Board type by the Python SDK.

As an example, I have made the following API call:

```
curl -s --request GET \
     --url 'https://api.getguru.com/api/v1/boards/home?collection=181e2522-f172-4bfe-808e-1dc41e62d04a' \
     --header 'accept: application/json' | jq '.items[] | select(.id=="9bde948d-7db6-4e4f-a455-2123d4d8f8dd")'
```

Here we are getting a collection of boards/board-groups and we are selecting from it a board group with ID `9bde948d-7db6-4e4f-a455-2123d4d8f8dd`. Now, here is what that object looks like (with company PII and some extraneous boards removed from the list):

```json
{
  "type": "section",
  "title": "Rules of engagement",
  "id": "9bde948d-7db6-4e4f-a455-2123d4d8f8dd",
  "items": [
    {
      "type": "fact",
      "itemId": "f66977fd-5e81-4c84-9c68-cb4a3f2edda5",
      "commentsEnabled": true,
      "id": "a8ed8734-eca2-4c2b-aaae-b1d8b8e51cf6",
      "lastModified": "2023-08-02T13:39:33.368+0000",
      "collection": {
        "name": "Sales",
        "id": "181e2522-f172-4bfe-808e-1dc41e62d04a",
        "color": "#FF8A65",
        "collectionType": "INTERNAL",
        "roiEnabled": false,
        "publicCardsEnabled": false,
        "collectionTypeDetail": "USER",
        "emoji": ":heavy_dollar_sign:"
      },
      "lastVerified": "2023-06-28T18:56:39.048+0000",
      "boards": [
        {
          "title": "Opportunity management",
          "id": "85d7d2aa-a395-4960-8329-ca77ad296f39",
          "items": [],
          "slug": "T6Xx9pgc/Opportunity-management",
          "numberOfFacts": 0
        },
        {
          "title": "Products and pricing",
          "id": "a91ec543-6f07-404f-8153-aafd8a246ffc",
          "items": [],
          "slug": "i7KxboxT/Products-and-pricing",
          "numberOfFacts": 0
        },
        {
          "title": "Rules of engagement",
          "id": "9bde948d-7db6-4e4f-a455-2123d4d8f8dd",
          "items": [],
          "slug": "iyMxnKyT/Rules-of-engagement",
          "numberOfFacts": 0
        }
      ],
      "shareStatus": "PUBLIC",
      "preferredPhrase": "Sales concession policy",
      "dateCreated": "2023-06-28T18:11:27.046+0000",
      "slug": "TMn6Mb5c/Sales-concession-policy",
      "htmlContent": true,
      "highlightedAttachments": [],
      "contentSchemaVersion": "1.0.0",
      "followed": false,
      "cardType": "CARD",
      "nextVerificationDate": "2023-08-02T13:39:43.144+0000",
      "verificationState": "NEEDS_VERIFICATION"
    },
    {
      "type": "board",
      "itemId": "50710906-33ba-49b6-9509-7bbf041969cf",
      "title": "Overview",
      "id": "e29471da-fdac-4df0-8658-0a3a9c284923",
      "lastModified": "2022-10-31T17:48:46.554+0000",
      "items": [],
      "slug": "TjAKryGc/Overview",
      "numberOfFacts": 1,
      "legacyType": "BOARD"
    },
  ],
  "slug": "iyMxnKyT/Rules-of-engagement",
  "itemId": "dee859e1-50ef-4413-a748-ab75c9f42e62",
  "legacyType": "BOARD_GROUP"
}
```

We can see here that this first item of the board group is of type "fact", not board. Yet the Python SDK here is going to cast it as a Board with the following attributes (this is the output of calling board.json() on this "board"):

```python
{'id': 'a8ed8734-eca2-4c2b-aaae-b1d8b8e51cf6', 'type': 'board', 'title': None, 'items': [], 'collection': {'id': '181e2522-f172-4bfe-808e-1dc41e62d04a', 'name': 'Sales', 'type': 'INTERNAL', 'color': '#FF8A65'}
```

If we now try to call get_board() on this Board.id, the call with 404 and we essentially cannot interact with it properly, as it really is not a board. In fact, if I call the card endpoint with this "board" ID, I get a valid card response.

This really causes problems, because it becomes impossible to trust the type system and type attributes of the objects within a board-group, not to mention a ton of data about the underlying object is lost during the bad casting to Board-type. The only way to know if a particular "Board" is really a card or not is to try calling get_board() with it and if that fails, try calling get_card() with it.

**Comment by dephekt** [comment]
Yeah, I understand the changes breaking things. The problem is this should be a stable API and a "deprecation" shouldn't break existing code. We had production DR/BC pipelines relying on a stable API which suddenly broke overnight without any changes on our end, which required a non-trivial refactoring of code which was heavily reliant on the existing boards paradigm.

Some effort to maintain backwards compatibility here should have been made or the underlying API should have been versioned appropriately. E.g. non-backward compatible changes to the API shouldn't have been pushed into the existing v1 API endpoints. Code using the same version of the SDK and API shouldn't break overnight.

**Comment by markhornak** [comment]
it's a fair argument.  we generally make our api changes in a non-breaking, backwards compatible way.  in this particular case we weighed the options and this was the best path forward to mitigate issues across the entire solution.  Regardless, it doesn't change the end result for the customer having to account for this.  Our CSM teams reached out very early in the planning stages to let the Champs know about this change and get the information surfaced to those customers, but it's not a perfect process either...

**Comment by dephekt** [comment]
I do understand that the fundamental nature of the boards to folders changes would be hard to do in a backwards compatible way. I'm certain it could be done, but no doubt would have introduced a decent amount of complexity on your end for something that is now considered legacy. So I do understand the conundrum and reasoning there. I'm also glad it happened because the previous way was pretty needlessly complicated versus the new folders stuff.

It's just there's a difference between "hey this thing is going away, make sure to update your code in the next e.g. 3-6 months" versus "hey, this thing just stopped working, drop everything _right now_ to update your code because now you're breaching your RPO".

Our point person for Guru is non-technical (e.g. she's not an engineer) and the issue of breaking API changes wasn't clearly indicated in communications to her. The conversations were essentially akin to [this post](https://community.getguru.com/announcements-8/important-navigation-and-hierarchy-update-coming-soon-7046). And in there, the language about the API changes is confusing:
> API AND SDK USERS: We advise not setting up new API or SDK calls to Boards until these updates have been released. Our API and SDK documentation will be updated to reflect the new folder structure. Stay tuned for more details!

Which reads more like, "Don't write new code using the boards endpoints for now". It's not really called out clear here "if you have existing code using the boards endpoints you must change them before X date or your stuff will break."

In any case, this isn't your problem personally, it's a communications issue elsewhere and something we can take up at the CSM level, I just wanted to clarify that since I brought up the frustration about the breaking API changes.

**Comment by markhornak** [comment]
We completely understand the impacts to you here, and do apologize, we take all this feedback in and learn from it for any future work we do including making sure we bring the importance of changes like this up through our CSMs more clearer.  Engineering owns this and will look to make sure we do better for our API/SDK users in the future!
