### ISSUE TITLE
Invalid Escape Sequence in `guru/bundle.py`

### ISSUE THREAD

**Issue by crockeo** [guruhq/py-sdk#76]
Invalid escape sequence in `guru/bundle.py`:

https://github.com/guruhq/py-sdk/blob/8b6881689eecb98d2f07b4da65b368276d31b9e2/guru/bundle.py#L358

Hi! I'm working on onboarding a project to use Bazel for our test suite, and our tests are failing like so:

```
INTERNALERROR>   File "/opt/app/bazel-bin/unit.runfiles/python_deps_guru/site-packages/guru/bundle.py", line 358
INTERNALERROR>     len(re.split("\s+", doc.text)),            # word count
INTERNALERROR>                  ^^^^^
INTERNALERROR> SyntaxError: invalid escape sequence '\s'
```

It looks like it's because the line linked above is trying to create a regex, but is missing the `r` prefix for the string, so `\s` is being interpreted as an escape character, rather than the string `r"\s+"`.

**Comment by markhornak** [comment]
Updated
